---

- name: 停止 firewalld 防火墙
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: 添加新的用户
  user:
    name: '{{ user_name }}'
    state: present
    groups: wheel
    append: yes

- name: 让用户可以使用 ssh 密钥登录
  authorized_key:
    user: '{{ item }}'
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    state: present
  with_items:
    - root
    - '{{ user_name }}'
